apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
  namespace: argocd
spec:
  destination:
    namespace: application-1
    server: 'https://kubernetes.default.svc'
  source:
    path: sample
    repoURL: 'https://github.com/Akashroy2323/argocd.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
